# Generated by Django 3.1.7 on 2021-03-14 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('naver_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('naver_review', models.TextField()),
                ('rating', models.IntegerField()),
                ('date_created', models.DateField()),
                ('naver_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naver_reviews', to='naver_products.naverproduct')),
            ],
            options={
                'verbose_name_plural': 'Naver Reviews',
            },
        ),
    ]
