# Generated by Django 3.1.7 on 2021-03-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naver_products', '0003_auto_20210317_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naverproduct',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='naverproduct',
            old_name='search_keyword',
            new_name='search_keywords',
        ),
        migrations.RenameField(
            model_name='naverproduct',
            old_name='seller',
            new_name='sellers',
        ),
    ]
