# Generated by Django 3.1.7 on 2021-03-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver_products', '0004_auto_20210320_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naverproduct',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='naverproduct',
            name='url',
            field=models.CharField(max_length=1500),
        ),
    ]
