# Generated by Django 3.2 on 2021-06-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_users', '0001_initial'),
        ('instagram_reviews', '0002_auto_20210316_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramreview',
            name='review_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instagramreview',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_reviews', to='instagram_users.instagramuser'),
        ),
    ]
