# Generated by Django 3.2 on 2021-07-09 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_reviews', '0003_auto_20210624_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramreview',
            old_name='review_likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='instagramreview',
            old_name='instagram_review',
            new_name='text',
        ),
    ]
