# Generated by Django 3.2 on 2021-07-09 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_reviews', '0004_auto_20210709_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramreview',
            options={'verbose_name': 'Instagram Review'},
        ),
    ]
