# Generated by Django 3.2 on 2021-06-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instagram_products', '0007_remove_instagramproduct_search_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('influencer', 'Influencer'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('insta_id', models.CharField(max_length=20)),
                ('count_all_posting', models.IntegerField(default=0)),
                ('follower', models.IntegerField()),
                ('recent_posts', models.ManyToManyField(blank=True, related_name='recent_posts', to='instagram_products.InstagramProduct')),
            ],
            options={
                'verbose_name_plural': 'Instagram Users',
            },
        ),
    ]
