# Generated by Django 3.2 on 2021-07-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_users', '0002_auto_20210624_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramuser',
            name='count_all_posting',
        ),
        migrations.RemoveField(
            model_name='instagramuser',
            name='recent_posts',
        ),
        migrations.RemoveField(
            model_name='instagramuser',
            name='type',
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='influencer',
            field=models.BooleanField(default=False),
        ),
    ]
