# Generated by Django 3.1.7 on 2021-03-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramHashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('writer', models.CharField(max_length=20)),
                ('date_created', models.DateField()),
                ('text', models.CharField(max_length=200)),
                ('likes', models.IntegerField()),
                ('is_ad', models.BooleanField(default=False)),
                ('instagram_hash_tag', models.ManyToManyField(blank=True, related_name='instagram_products', to='instagram_products.InstagramHashTag')),
            ],
            options={
                'verbose_name_plural': 'Instagram Post',
            },
        ),
        migrations.CreateModel(
            name='InstagramPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='instagram_photos')),
                ('instagram_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_photos', to='instagram_products.instagramproduct')),
            ],
            options={
                'verbose_name_plural': 'Instagram Photos',
            },
        ),
    ]
