# Generated by Django 3.1.7 on 2021-03-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_products', '0004_auto_20210316_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Search Keywords',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='instagramhashtag',
            options={'verbose_name_plural': 'Instagram Hash Tags'},
        ),
        migrations.AlterModelOptions(
            name='instagramuser',
            options={'verbose_name_plural': 'Instagram Users'},
        ),
        migrations.AddField(
            model_name='instagramproduct',
            name='search_keyword',
            field=models.ManyToManyField(blank=True, related_name='instagram_products', to='instagram_products.SearchKeyword'),
        ),
    ]
