# Generated by Django 3.2 on 2021-06-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_reviews', '0003_auto_20210624_2032'),
        ('instagram_products', '0007_remove_instagramproduct_search_keywords'),
        ('instagram_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramproduct',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_products', to='instagram_users.instagramuser'),
        ),
        migrations.DeleteModel(
            name='InstagramUser',
        ),
        migrations.DeleteModel(
            name='SearchKeyword',
        ),
    ]
