# Generated by Django 3.2 on 2021-07-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_products', '0008_auto_20210624_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Searched Keyword',
            },
        ),
        migrations.AlterModelOptions(
            name='instagramhashtag',
            options={'verbose_name': 'Instagram Hash Tag'},
        ),
        migrations.AlterModelOptions(
            name='instagramphoto',
            options={'verbose_name': 'Instagram Photo'},
        ),
        migrations.AlterModelOptions(
            name='instagramproduct',
            options={'verbose_name': 'Instagram Product'},
        ),
        migrations.AddField(
            model_name='instagramproduct',
            name='searched_keywords',
            field=models.ManyToManyField(blank=True, related_name='instagram_products', to='instagram_products.SearchedKeyword'),
        ),
    ]
