# Generated by Django 3.2.5 on 2021-07-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_products', '0009_auto_20210709_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Caption',
            },
        ),
        migrations.AddField(
            model_name='instagramproduct',
            name='visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instagramproduct',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagramphoto',
            name='caption',
            field=models.ManyToManyField(blank=True, related_name='instagram_photos', to='instagram_products.Caption'),
        ),
    ]
