# Generated by Django 3.2.5 on 2021-07-13 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_products', '0010_auto_20210713_0912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caption',
            new_name='PhotoCaption',
        ),
        migrations.AlterModelOptions(
            name='photocaption',
            options={'verbose_name_plural': 'Photo Caption'},
        ),
    ]
